# Generated by Django 3.2 on 2023-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230121_1845'),
        ('reviews', '0002_comment_review'),
    ]

    operations = [
    ]
