# Generated by Django 3.2 on 2023-01-25 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230125_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите не ниже 1'), django.core.validators.MaxValueValidator(10, message='Введите оценку не выше 10')], verbose_name='Оценка'),
        ),
    ]
